import { CategoryType, ICategory } from "../../../models/category.model";

export const CategoriesMockup: CategoryType[] = [
  {
    name: "Food & Drinks",
    name_th: "อาหารและเครื่องดื่ม",
    icon: "MdFastfood",
    color: "#FF9800",
  },
  {
    name: "Groceries",
    name_th: "ของใช้ในครัวเรือน",
    icon: "MdLocalGroceryStore",
    color: "#4CAF50",
  },
  {
    name: "Transport",
    name_th: "ค่าเดินทาง",
    icon: "MdDirectionsCar",
    color: "#2196F3",
  },
  {
    name: "Shopping",
    name_th: "ช้อปปิ้ง",
    icon: "MdShoppingCart",
    color: "#E91E63",
  },
  {
    name: "Health & Wellness",
    name_th: "สุขภาพและการแพทย์",
    icon: "MdLocalHospital",
    color: "#F44336",
  },
  {
    name: "Entertainment",
    name_th: "บันเทิง",
    icon: "MdMovie",
    color: "#9C27B0",
  },
  {
    name: "Bills & Utilities",
    name_th: "ค่าสาธารณูปโภค",
    icon: "MdReceipt",
    color: "#3F51B5",
  },
  {
    name: "Education",
    name_th: "การศึกษา",
    icon: "MdSchool",
    color: "#FFEB3B",
  },
  {
    name: "Travel",
    name_th: "ท่องเที่ยว",
    icon: "MdFlight",
    color: "#00BCD4",
  },
  {
    name: "Home & Rent",
    name_th: "ค่าที่พักและค่าเช่า",
    icon: "MdHome",
    color: "#795548",
  },
  {
    name: "Insurance",
    name_th: "ประกันภัย",
    icon: "MdSecurity",
    color: "#607D8B",
  },
  {
    name: "Electronics & Gadgets",
    name_th: "อุปกรณ์อิเล็กทรอนิกส์",
    icon: "MdDevices",
    color: "#2196F3",
  },
  {
    name: "Salary",
    name_th: "เงินเดือน",
    icon: "MdAttachMoney",
    color: "#4CAF50",
  },
  {
    name: "Investments",
    name_th: "การลงทุน",
    icon: "MdTrendingUp",
    color: "#FF5722",
  },
  {
    name: "Savings",
    name_th: "เงินออม",
    icon: "MdSavings",
    color: "#8BC34A",
  },
  {
    name: "Taxes",
    name_th: "ภาษี",
    icon: "MdAccountBalance",
    color: "#607D8B",
  },
  {
    name: "Subscriptions",
    name_th: "ค่าสมาชิกและบริการรายเดือน",
    icon: "MdSubscriptions",
    color: "#FF9800",
  },
  {
    name: "Gifts & Donations",
    name_th: "ของขวัญและการบริจาค",
    icon: "MdCardGiftcard",
    color: "#FF4081",
  },
  {
    name: "Fitness",
    name_th: "ฟิตเนสและออกกำลังกาย",
    icon: "MdFitnessCenter",
    color: "#76FF03",
  },
  {
    name: "Beauty & Personal Care",
    name_th: "ความงามและดูแลตัวเอง",
    icon: "MdSpa",
    color: "#E91E63",
  },
  {
    name: "Pets",
    name_th: "สัตว์เลี้ยง",
    icon: "MdPets",
    color: "#FF9800",
  },
  {
    name: "Car Maintenance",
    name_th: "ค่าบำรุงรักษารถ",
    icon: "MdBuild",
    color: "#607D8B",
  },
  {
    name: "Childcare",
    name_th: "ค่าดูแลเด็ก",
    icon: "MdChildCare",
    color: "#FFEB3B",
  },
  {
    name: "Work Expenses",
    name_th: "ค่าใช้จ่ายเกี่ยวกับงาน",
    icon: "MdWork",
    color: "#3F51B5",
  },
  {
    name: "Gaming",
    name_th: "เกมและอีสปอร์ต",
    icon: "MdSportsEsports",
    color: "#FF5722",
  },
];
